### ISSUE TITLE
Request for mod update to support latest version

### ISSUE THREAD

**Issue by Virtualmachine2020** [jtl-elisa/HUB-Better-Villages#132]
BRO ITS BEEN SO LONG PLEASE ALREADY UPDATE THIS MOD IT'S SO OUTDATED

**Comment by jtl-elisa** [comment]
Hi! Thank you for your interest in the mod! I understand you're excited for an update. She'll be arriving shortly.
Have a nice day.

**Comment by Virtualmachine2020** [comment]
when will it arrive?
