### ISSUE TITLE
offer

### ISSUE THREAD

**Issue by daterbro** [jtl-elisa/HUB-Better-Villages#134]
Hello, your mod is a phenomenon, many can't imagine life without it, like me. I understand that updating Java from 17 to 21 can cause problems, but if you look at many other mods, this should not affect. We all ask you to update the mod to 1.21.1, because now this is the most popular version for mods, this is the future 1.12.2 or 1.16.5 is a new hit version and the sooner you get into it the better, thank you!

**Comment by jtl-elisa** [comment]
Please use the search bar, This question was already answered a few days ago.
like [#116 ](https://github.com/jtl-elisa/HUB-Better-Villages/issues/116)
> hey, sorry no ETA. but it will arrive soon. thanks you for your patience.

**Comment by daterbro** [comment]
Ладно, буду ждать! Спасибо!

**Comment by jtl-elisa** [comment]
Sorry I don't understand Russian :/

**Comment by daterbro** [comment]
excuse my Russian, I'm just from Ukraine, thank you so much that the release will be this month, I contacted many mod developers, and they all answered crudely, and you are so sociable! have a nice holiday to you too

**Comment by jtl-elisa** [comment]
> Sorry to bother you again, I wanted to ask, will you just update the version or will you add new villages?? Both options suit me

No problem, feel free to ask! 

Yes of course. However, **before introducing new villages**, our current priority is to stabilize the project and **ensure compatibility with some essential mods**. Once we've achieved a stable foundation, we'd be delighted to explore adding new features, including additional villages. 

---

> excuse my Russian, I'm just from Ukraine, thank you so much that the release will be this month, I contacted many mod 
   developers, and they all answered crudely, and you are so sociable! have a nice holiday to you too
   
Thank you so much for your kind words! We’re glad you find our approach sociable—it’s something we truly value.

Note: Many developers on the minecraft communauty work on their projects in their free time, alongside other responsibilities. 

Questions about release dates or timelines can sometimes feel like added pressure, which might explain the responses you received. 

Additionally, language differences and the lack of tone in written communication online can sometimes lead to misunderstandings between parties. **Of course, this is just my perspective**,  but yes **that doesn't justify everything**.

**Comment by daterbro** [comment]
Thank you, good luck!
