### ISSUE TITLE
broken greenhouse with the agricraft mod pls help T-T 

### ISSUE THREAD

**Issue by kIENNGUYN** [jtl-elisa/HUB-Better-Villages#99]
![Screenshot (89)](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/157450282/2bf0cbf6-8d56-4f53-ba1d-68039f187348)
broken greenhouse with the agricraft any idea to fix pls help me

**Comment by jtorleonstudios** [comment]
Hi, What exactly is the problem? I don't recognize this structure. Is it from agricraft?

**Comment by kIENNGUYN** [comment]
HI, sorry for late reply and yes it from the Agricraft

**Comment by kIENNGUYN** [comment]
> Hi, What exactly is the problem? I don't recognize this structure. Is it from agricraft? 
ye its from agricraft and i dont know where to ask abt it idk if it made by better villager or agricraft
